### ISSUE TITLE
Clean UP & Dockerization eos6m4j

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos6m4j#1]

**Comment by samuelmaina** [comment]
HI @GemmaTuron 
I have a raised a PR.
Able to fetch and  predicted with all smiles having vals. 
 - [eos6m4j_cli_fetch.log](https://github.com/ersilia-os/eos6m4j/files/11931213/eos6m4j_cli_fetch.log)
 - [eos6m4j_cli_eml_pred.csv](https://github.com/ersilia-os/eos6m4j/files/11931215/eos6m4j_cli_eml_pred.csv)

**Comment by samuelmaina** [comment]
@GemmaTuron , the model is failing on Testing on PR step. I examined the issue and it seems the error emerges in the  prediction stage and here is the error 
```
api_instance = self._get_api_instance(api_name=api_name)
  File "/usr/share/miniconda/lib/python3.10/site-packages/ersilia/core/model.py", line 181, in _get_api_instance
    len(api_names) == 1
AssertionError: More than one API found, please specificy api_name
```
The model has 2 api for generating molecular maps either as descriptors (`ersilia api descriptors`)  or fingerprints `ersilia api fingerprints `) .The default `ersilia run`  calls `ersilia api descriptors` when I test with eml data locally .  The service.py doesn't have run as one of the model functions but other models have this method. My guess is that the workflow is calling `ersilia api` either without any method or with  with `run` or `predict`. I think if `api` is used, then the following method must be explicitly stated in the service.py.

**Comment by GemmaTuron** [comment]
@samuelmaina 

Indeed that was one of the reasons we used to have more than one API. What we have decided to do is to only have a run API, which means this model needs to be divided in two, `bidd-molmap-descriptors` and `bidd-molmap-fps`.
Would you open a Model Request for the `bidd-molmap-fps`, and once this is done, we will eliminate them from here? 
The steps would be:
1. Open a Model Request issue for the `bidd-molmap-fps` (copy the information from this model)
2. Copy the code without any refactoring and just eliminating the part that runs the descriptors 
3. Once we see that this works, we will attempt a small refactoring to the eos-template format

**Comment by samuelmaina** [comment]
Hi @GemmaTuron, thanks ,Sorry for the late reply. I will do  this and  see how this goes.

**Comment by samuelmaina** [comment]
I able to run and predict a csv file  with the run.sh with the descriptor alone
```
(eos6m4j) samuelmayna@SAM:~/ersilia_github_models$ cd eos6m4j/model/framework
(eos6m4j) samuelmayna@SAM:~/ersilia_github_models/eos6m4j/model/framework$ bash run.sh ./ ../../../sample_input.csv output.csv
Loading config /home/samuelmayna/ersilia_github_models/eos6m4j/model/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_cosine.cfg.gzip
Loading config /home/samuelmayna/ersilia_github_models/eos6m4j/model/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_scale.cfg.gzip
Loading config /home/samuelmayna/ersilia_github_models/eos6m4j/model/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_scale.cfg.gzip
100%|###################################################################################################################################| 28/28 [00:34<00:00,  1.18it/s]
(eos6m4j) samuelmayna@SAM:~/ersilia_github_models/eos6m4j/model/framework$
```
but I am getting this error when  fetching .
```
EmptyOutputError

Detailed error:
Model API eos6m4j:run did not produce an output
  0%|          | 0/2 [00:00<?, ?it/s]Loading config /home/samuelmayna/eos/repository/eos6m4j/20230703160033_6933F8/eos6m4j/artifacts/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_cosine.cfg.gzip
Loading config /home/samuelmayna/eos/repository/eos6m4j/20230703160033_6933F8/eos6m4j/artifacts/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_scale.cfg.gzip
Loading config /home/samuelmayna/eos/repository/eos6m4j/20230703160033_6933F8/eos6m4j/artifacts/framework/code/scripts/../bidd-molmap/molmap/config/descriptor_scale.cfg.gzip

100%|##########| 2/2 [00:00<00:00, 22.71it/s]


Hints:
- Visit the fetch troubleshooting site
```
It is the same error  as this https://github.com/ersilia-os/eos1amr/issues/1#issuecomment-1614793220

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Please, attach the whole log of the error, have you cloned the repo locally and checked that these files are available there and then fetched from -repo_path?

**Comment by samuelmaina** [comment]
I have fetched the model locally and it was running when the two api endpoints were there. I have removed the fingerprint model  . The model is failing after modification. Here are the complete logs 
[eos6m4j_cli_fetch.log](https://github.com/ersilia-os/eos6m4j/files/11938709/eos6m4j_cli_fetch.log)
I have not raised a new model suggesting for the fingerprint version but I will later.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

Please read my instructions again:

1. Open a Model Request issue for the bidd-molmap-fps (copy the information from this model)
2. Copy the code without any refactoring and just eliminating the part that runs the descriptors
3. Once we see that this works, we will attempt a small refactoring to the eos-template format

**Do Not modify THIS repository,** open a new one and we will work on that one until we are sure the new model is working. So we always have the original code

**Comment by samuelmaina** [comment]
okay .  I will  undo the changes  and do the suggestion.

**Comment by samuelmaina** [comment]
@GemmaTuron , I have raised the issue  at https://github.com/ersilia-os/ersilia/issues/736

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
I have modified the PR , https://github.com/ersilia-os/eos6m4j/pull/2. I started the refactoring process anew and  I didn't get the issues  https://github.com/ersilia-os/eos6m4j/issues/1#issuecomment-1618298503 when changing  the service.py to the standard  service.py. I  don't have  a clear reason why this is the case.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

I will not merge this PR until the new model is tested and working. 
To understand, you are using the eos6m4j for the descriptors and the eos59rr for the fingerprints?
Please make sure to reflect that on both model alias

**Comment by samuelmaina** [comment]
@GemmaTuron , I am  using this model for the descriptors  and  eos59rr for the fingerprints . I have changed the alias of  this model to bidd-molmap-dsp.
